import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";
import { copyFile } from "node:fs/promises";

const banner = `/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n*/`;

const production = process.argv[2] === "production";
const outfile = "dist/plugin/main.js";
const builtins = [...new Set(builtinModules.flatMap((name) => [name, `node:${name}`]))];

const context = await esbuild.context({
  banner: { js: banner },
  bundle: true,
  entryPoints: ["main.ts"],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  logLevel: "info",
  minify: production,
  outfile,
  sourcemap: production ? false : "inline",
  target: "es2020",
  treeShaking: true,
});

if (production) {
  await context.rebuild();
  await copyFile(outfile, "main.js");
  process.exit(0);
}

await context.watch();
